language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer

notifications:
  email:
    recipients:
    - juanmanuelstraus@gmail.com
    - brandanricardo@yahoo.com.ar
    - camila.15694@gmail.com
    on_failure: always
